### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by fallen97** [Kodatos/Cumulonimbus#1]
Building the apk and running it causes it to crash. Tested on 5.0, 6.0 and 7.0.

**Comment by Kodatos** [comment]
I have not uploaded any API keys in order to not exceed the OpenWeatherMap limits.
Neither have I uploaded any pictures or closed source fonts I haven't decided on yet.
If the issue is anything other than those, I need more info.

**Comment by Kodatos** [comment]
Added unversioned files in commit: 719b45fc1f738f15295b74d1ec61489b45e178eb and added a placeholder string for the API key. Apply for it yourself.
If you have any other issue, post a new one with appropriate logs.
