### ISSUE TITLE
App freezes on logo after intro, even after adding API key

### ISSUE THREAD

**Issue by Aym9n** [Kodatos/Cumulonimbus#3]
![screenshot_2018-07-29-13-02-19](https://user-images.githubusercontent.com/36565843/43366118-c0e7f910-932f-11e8-803d-bfe0002d3a54.png)

**Comment by Kodatos** [comment]
I need some more information, mainly **logs** and your **android version**. I currently don't have time to actively look into the issues, so I need more input from you.
Paste your logs in pastebin or similar and comment the link here.

**Comment by Kodatos** [comment]
Closing issue as no response received from @Aeg0nTargaryen
